server:
  port: ${HTTP_PORT:8081}
  servlet:
    context-path: /ygo
    session:
      timeout: 120m
  error:
    include-message: always

spring:
  application:
    name: ygo
  datasource:
    url: jdbc:mysql://localhost:3333/ygo?allowPublicKeyRetrieval=true&useSSL=false
    username: ygo
    password: ygopass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: off
    open-in-view: false
    properties:
      hibernate:
        format_sql: none

app:
  config:
    ygoprodeck:
      base-url: https://db.ygoprodeck.com/api/v7/
      card-info: cardinfo.php

jwt:
  secret: 7aMdK2qPfX9sVb3GnLr1Tc8WyJ0HzBvE
  header: Authorization

api:
  key: s3cr7s_Xy9Kp30vQg5R8TgA1LcZ8WuJfHAlBtDS


